import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    const MethodChannel channel = MethodChannel('easebuzz');
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          String accessKey =
              "555a2b009214573bd833feca997244f1721ac69d7f2b09685911bc943dcf5201";
          // "Access key generated by the Initiate Payment API";
          String payMode = "test";
          //"This will either be "test" or "production"";
          Object parameters = {
            "accessKey": accessKey,
            "payMode": payMode,
          };
          try {
            final paymentResponse =
                await channel.invokeMethod("payWithEasebuzz", parameters);
            log("\n\nPayment Response :: $paymentResponse\n\n");
            /* paymentResponse is the HashMap containing the response of the payment.
You can parse it accordingly to handle response */
          } catch (e) {
            log("\n\nPayment error :: $e\n\n");
          }
        },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
